### ISSUE TITLE
History is not supported?

### ISSUE THREAD

**Issue by GNURub** [centrifugal/helm-charts#3]
In full values i dont see history settings, is possible to add?

[https://github.com/centrifugal/helm-charts/blob/master/charts/centrifugo/values.yaml](values.yaml)

**Comment by FZambia** [comment]
Hello, you can run chart with your `values.yaml` where you set all required options inside:
```
centrifugo:
  config:
``` 
section. This will be then transformed to `config.json` for Centrifugo.

So you can define all options that Centrifugo has. It's also possible to provide namespace configuration over environment variables when running chart.

I think this [already mentioned in chart readme](https://github.com/centrifugal/helm-charts/tree/master/charts/centrifugo#configuration). Is this what you asked about?

**Comment by GNURub** [comment]
thanks!
