### ISSUE TITLE
[bug] existingSecret keys inconsistency

### ISSUE THREAD

**Issue by masgustavos** [centrifugal/helm-charts#33]
**Describe the bug**

The [README file states](https://github.com/centrifugal/helm-charts/blob/centrifugo-7.4.2/charts/centrifugo/README.md?plain=1#L99) that the `existingSecret` must contain the keys described "below", which are in camel case. However, [the chart extract secret values](https://github.com/centrifugal/helm-charts/blob/centrifugo-7.4.2/charts/centrifugo/templates/deployment.yaml#L67) with snake case keys.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.12-eks-a64ea69
```

**Which version of the chart**: 7.4.2

**What happened**: Got an error with secret value fetching, since my keys were in camel case and the chart expects snake case

**What you expected to happen**: I don't think the choice of case matters, as long as it is consistent. If camel case is used under the `secrets` property, camel case should be expected in the `existingSecret` as well.

**How to reproduce it** (as minimally and precisely as possible): Deploy the chart with a `existingSecret` that has the same keys under the `secret` property.

**Anything else we need to know**: Not really, thanks for the chart and making our lives easier. This is nitpicking, and from the container logs the solution was obvious!

**Comment by FZambia** [comment]
@masgustavos hello! Thanks for reporting, could you take a look at #34 ?
