### ISSUE TITLE
[bug] scaling with redis config no longer accurate for v4.0.0

### ISSUE THREAD

**Issue by ssnt** [centrifugal/helm-charts#36]
**Describe the bug**

The config sections for Redis in the 'scaling with redis' section are no longer accurate (at least for the Redis Sentinel example)

An incorrect password-less Redis instance is created, and the config flags for centrifugo v4.0.0 are incorrect for redis in sentinel mode

**Which version of the chart**:

v9.0.0

**What happened**:

Followed the example scale with redis documentation and centrifugo would not connect to Redis

**What you expected to happen**:

Following the example starts a minimal working centrifugo cluster

**How to reproduce it** (as minimally and precisely as possible):

values.yaml 

```
config:
  engine: redis
  redis_master_name: <REDIS MASTER SET NAME>
  redis_sentinels: <REDIS SENTINELS SERVICE>
```

```
helm install centrifugo-ex centrifugal/centrifugo --version version --values values.yaml
```

Centrifugo will try and connect to a redis instance on localhost because the config keys are not used in v4.0.0 so will fail to start

**Suggested Fix**

Redis needs different flags for the password-less example given 

Replace;

`helm install redis bitnami/redis --set usePassword=false --set cluster.enabled=true --set sentinel.enabled=true`

with

`helm install redis bitnami/redis --set auth.enabled=false --set cluster.enabled=true --set sentinel.enabled=true`

That launches a correct password-less Redis sentinel cluster

The config keys for redis sentinel are incorrect too and are not recognised and used by centrifugo

Replace

`config.redis_master_name` with `config.redis_sentinel_master_name`

And

`config.redis_sentinels` with `config.redis_sentinel_address`

**Comment by ssnt** [comment]
I have also just noticed that the `NOTES.txt` calls out for the user to port forward port `8080` once launched, the admin UI by default in v4.0.0 is on port `8000`

**Comment by FZambia** [comment]
@ssnt hello, thanks! Actually seems that all this problems equally true for v3 - Redis configuration changed in Centrifugo v3, and seems that `bitnami/redis` was updated at some point.

And note about admin UI is also true.

Any chance you can send PR with fixes or prefer me to deal with this?

**Comment by ssnt** [comment]
> @ssnt hello, thanks! Actually seems that all this problems equally true for v3 - Redis configuration changed in Centrifugo v3, and seems that `bitnami/redis` was updated at some point.
> 
> And note about admin UI is also true.
> 
> Any chance you can send PR with fixes or prefer me to deal with this?

If you don't mind I will leave this to you, I have not cloned this repo I am using it with my own `values.yaml` file directly from helm

I also don't want to only fix half of the information, I only tested with my use case of Redis + Sentinel so I have a feeling there may be more that needs changing I am not aware of!
