### ISSUE TITLE
[bug] Error on deploy "404 page not found"

### ISSUE THREAD

**Issue by michelandres** [centrifugal/helm-charts#37]
**Describe the bug**
After deploy the helm chart in DO Kubernetes, I can't access to admin panel, API or other service, I always get the message "404 page not found"

**Version of Helm and Kubernetes**:

Helm Version:

```console
{
   "Version":"v3.9.0",
   "GitCommit":"7ceeda6c585217a19a1131663d8cd1f7d641b2a7",
   "GitTreeState":"clean",
   "GoVersion":"go1.17.5"
}
```

Kubernetes Version:

```console
Client Version: version.Info
{
   "Major":"1",
   "Minor":"24",
   "GitVersion":"v1.24.0",
   "GitCommit":"4ce5a8954017644c5420bae81d72b09b735c21f0",
   "GitTreeState":"clean",
   "BuildDate":"2022-05-03T13:46:05Z",
   "GoVersion":"go1.18.1",
   "Compiler":"gc",
   "Platform":"windows/amd64"
}

Kustomize Version: v4.5.4

Server Version: version.Info
{
   "Major":"1",
   "Minor":"23",
   "GitVersion":"v1.23.9",
   "GitCommit":"c1de2d70269039fe55efb98e737d9a29f9155246",
   "GitTreeState":"clean",
   "BuildDate":"2022-07-13T14:19:57Z",
   "GoVersion":"go1.17.11",
   "Compiler":"gc",
   "Platform":"linux/amd64"
}
```

**Which version of the chart**:
9.0.0

**What happened**:
When access to https://host.com:8000 I always get the message "404 page not found"

**What you expected to happen**:
Access to https://host.com:8000 and load admin UI

**How to reproduce it** (as minimally and precisely as possible):
Deploy the last helm chart with ingress. I tried port forwarding and got the same error.

**Anything else we need to know**:
When I logged into the pod and run "./centrifugo --health" I get 

2022-07-28 16:38:55 [FTL] ListenAndServe: listen tcp: address :tcp://10.245.143.84:8000: too many colons in address

**Comment by FZambia** [comment]
@michelandres hello, can you reproduce the same with minikube?

**Comment by FZambia** [comment]
> When I logged into the pod and run "./centrifugo --health" I get
> 2022-07-28 16:38:55 [FTL] ListenAndServe: listen tcp: address :tcp://10.245.143.84:8000: too many colons in address

That's because k8s usually has port env var that conflicts with Centrifugo port. If you run `./centrifugo --health --port 8000` you most probably get another error as command line arguments has a priority over env. But not sure why you are trying to run centrifugo from the container though.

**Comment by michelandres** [comment]
I'm not trying to run centrifugo from the container, only run "./centrifugo --health" in the container to check what happened because I'm getting the “404 page not found” error. Frist, I think was a problem of ingress and then did a port forwarding "kubectl port-forward centrifugo-6dbfd855f8-lsqzz  8000:8000" and when try to access to http://localhost:8000/ I get "404 page not found” error again.

**Comment by michelandres** [comment]
> @michelandres hello, can you reproduce admin problem with minikube? Will be much simpler for me to try it out as I don't have access to DO k8s.

I've just test helm chart in my docker desktop kubernate distribution and I get the same error. When I try to access to http://127.0.0.1:8000 I get 404 page not found

![error_screen](https://user-images.githubusercontent.com/99357981/181619740-8122aeed-acef-4ca4-8b72-7290da2d9a5c.jpg)

**Comment by michelandres** [comment]
Sorry, Cloud you please close the bug?, in k8s admin UI works on port 9000 and isn't public, you need to access via port forwarding.
