### ISSUE TITLE
[enhancement] add autoscalingTemplate to hpa

### ISSUE THREAD

**Issue by mfuxi** [centrifugal/helm-charts#59]
**Is your feature request related to a problem? Please describe.**
Enhance the hpa template and improve the autoscaling so it could autoscale by Prometheus metrics

**Describe the solution you'd like**
Add the ability to use autoscalingTemplate

**Comment by FZambia** [comment]
Part of [10.0.3](https://github.com/centrifugal/helm-charts/releases/tag/centrifugo-10.0.3) - thanks @mfuxi !
