### ISSUE TITLE
[enhancement] Add possibility to configure Deployment annotations

### ISSUE THREAD

**Issue by begemotik** [centrifugal/helm-charts#83]
**Is your feature request related to a problem? Please describe.**
If `.Values.existingSecret` is used and all the sensitive data is created outside of Helm I need to be able to restart the pods in case any changes to the secret are detected. One of the options is to use [Reloader](https://github.com/stakater/Reloader) which triggers rollout when notices changes to the secret.

**Describe the solution you'd like**
To enable it there should be an option to add custom annotation to Deployment.

**Comment by FZambia** [comment]
Many thanks @begemotik - part of [v11.5.0](https://github.com/centrifugal/helm-charts/releases/tag/centrifugo-11.5.0)
