### ISSUE TITLE
[bug] Missing CENTRIFUGO_REDIS_USER in deployment object

### ISSUE THREAD

**Issue by mfuxi** [centrifugal/helm-charts#86]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.13-eks-508b6b3", GitCommit:"26dbbc7674e3d15b579cec35cdd6aede55c1d426", GitTreeState:"clean", BuildDate:"2024-01-29T20:58:43Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
9.1.2

**What happened**:
I wasn't able to connect centrifugo to AWS memorydb because of the lack of redis_user environment variable that should be referenced from the secret

**What you expected to happen**:
Centrifugo needs to be able to work with AWS memorydb as it's working with any other redis or redis-cluster

**How to reproduce it** (as minimally and precisely as possible):
Try connecting your Centrifugo instance to memorydb by using the suggested env vars such as: CENTRIFUGO_REDIS_ADDRESS and CENTRIFUGO_REDIS_PASSWORD
<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
key: value
```

```
helm install my-release centrifugal/centrifugo --version version --values values.yaml
```

-->

**Anything else we need to know**:
By adding that missing env var that would be referenced from the secret you'll be able to connect to any redis-cluster (including memorydb) using solely the env vars which are referenced from the secret

**Comment by FZambia** [comment]
Thanks, as noted in PR - missing secret vars could be set over `envSecret` https://github.com/centrifugal/helm-charts/blob/bddc91cce20ad759a6d1e63792768c6c6009ad39/charts/centrifugo/values.yaml#L266 - but having it explicit is less confusing and more straightforward.
